name: Reproduce Flaky Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: maven clean install 
        run: mvn clean install -pl hadoop-ozone -am -DskipTests -Dcheckstyle.skip -Drat.skip -U
        
      # - name: Compile Module
      #   run: mvn test-compile -am -Dcheckstyle.skip -Drat.skip -U
      - name: Check
        uses: actions/checkout@v3
        with:
          ref: 36901d4d4f1d88e3b3de636ad4c379eee67f5221
  
      - name: Test with Maven 
        run: | 
              for i in {1..100}; do mvn test -pl hadoop-ozone -am -Dtest=org.apache.hadoop.ozone.scm.TestSecretKeySnapshot#testInstallSnapshot -DfailIfNoTests=false -Drat.skip -fae>>test_log_HDDS-8839.txt || echo "Test iteration $i failed">>test_log_HDDS-8839.txt; done
              
      - name: Upload Test Log 
        if: always() 
        uses: actions/upload-artifact@v2 
        with: 
          name: test_log_HDDS-8839
          path: test_log_HDDS-8839.txt
